import React from 'react';

   
function CharacterSkills({ handleSubmit, skills, handleChange }) {
    return (
        <div>
            <form onSubmit={handleSubmit}>
                <div>
                    <label>
                        Acrobatics:
                        <input
                            type="number"
                            name="skills.acrobatics"
                            value={skills.acrobatics }
                            onChange={handleChange}
                            required
                        />
                    </label>
                    <label>
                        <input
                            type="checkbox"
                            name="skills.acrobatics_pro"
                            checked={skills.acrobatics_pro}
                            onChange={handleChange}
                        />
                        Proficient
                    </label>
                </div>
                <div>
                    <label>
                        Animal Handling:
                        <input
                            type="number"
                            name="skills.animal_handling"
                            value={skills.animal_handling}
                            onChange={handleChange}
                            required
                        />
                    </label>
                    <label>
                        <input
                            type="checkbox"
                            name="skills.animal_handling_pro"
                            checked={skills.animal_handling_pro}
                            onChange={handleChange}
                        />
                        Proficient
                    </label>
                </div>
                <div>
                    <label>
                        Arcana:
                        <input
                            type="number"
                            name="skills.arcana"
                            value={skills.arcana}
                            onChange={handleChange}
                            required
                        />
                    </label>
                    <label>
                        <input
                            type="checkbox"
                            name="skills.arcana_pro"
                            checked={skills.arcana_pro}
                            onChange={handleChange}
                        />
                        Proficient
                    </label>
                </div>
                <div>
                    <label>
                        Athletics:
                        <input
                            type="number"
                            name="skills.athletics"
                            value={skills.athletics}
                            onChange={handleChange}
                            required
                        />
                    </label>
                    <label>
                        <input
                            type="checkbox"
                            name="skills.athletics_pro"
                            checked={skills.athletics_pro}
                            onChange={handleChange}
                        />
                        Proficient
                    </label>
                </div>
                <div>
                    <label>
                        Deception:
                        <input
                            type="number"
                            name="skills.deception"
                            value={skills.deception}
                            onChange={handleChange}
                            required
                        />
                    </label>
                    <label>
                        <input
                            type="checkbox"
                            name="skills.deception_pro"
                            checked={skills.deception_pro}
                            onChange={handleChange}
                        />
                        Proficient
                    </label>
                </div>
                <div>
                    <label>
                        History:
                        <input
                            type="number"
                            name="skills.history"
                            value={skills.history}
                            onChange={handleChange}
                            required
                        />
                    </label>
                    <label>
                        <input
                            type="checkbox"
                            name="skills.history_pro"
                            checked={skills.history_pro}
                            onChange={handleChange}
                        />
                        Proficient
                    </label>
                </div>
                <div>
                    <label>
                        Insight:
                        <input
                            type="number"
                            name="skills.insight"
                            value={skills.insight}
                            onChange={handleChange}
                            required
                        />
                    </label>
                    <label>
                        <input
                            type="checkbox"
                            name="skills.insight_pro"
                            checked={skills.insight_pro}
                            onChange={handleChange}
                        />
                        Proficient
                    </label>
                </div>
                <div>
                    <label>
                        Intimidation:
                        <input
                            type="number"
                            name="skills.intimidation"
                            value={skills.intimidation}
                            onChange={handleChange}
                            required
                        />
                    </label>
                    <label>
                        <input
                            type="checkbox"
                            name="skills.intimidation_pro"
                            checked={skills.intimidation_pro}
                            onChange={handleChange}
                        />
                        Proficient
                    </label>
                </div>
                <div>
                    <label>
                        Investigation:
                        <input
                            type="number"
                            name="skills.investigation"
                            value={skills.investigation}
                            onChange={handleChange}
                            required
                        />
                    </label>
                    <label>
                        <input
                            type="checkbox"
                            name="skills.investigation_pro"
                            checked={skills.investigation_pro}
                            onChange={handleChange}
                        />
                        Proficient
                    </label>
                </div>
                <div>
                    <label>
                        Medicine:
                        <input
                            type="number"
                            name="skills.medicine"
                            value={skills.medicine}
                            onChange={handleChange}
                            required
                        />
                    </label>
                    <label>
                        <input
                            type="checkbox"
                            name="skills.medicine_pro"
                            checked={skills.medicine_pro}
                            onChange={handleChange}
                        />
                        Proficient
                    </label>
                </div>
                <div>
                    <label>
                        Nature:
                        <input
                            type="number"
                            name="skills.nature"
                            value={skills.nature}
                            onChange={handleChange}
                            required
                        />
                    </label>
                    <label>
                        <input
                            type="checkbox"
                            name="skills.nature_pro"
                            checked={skills.nature_pro}
                            onChange={handleChange}
                        />
                        Proficient
                    </label>
                </div>
                <div>
                    <label>
                        Perception:
                        <input
                            type="number"
                            name="skills.perception"
                            value={skills.perception}
                            onChange={handleChange}
                            required
                        />
                    </label>
                    <label>
                        <input
                            type="checkbox"
                            name="skills.perception_pro"
                            checked={skills.perception_pro}
                            onChange={handleChange}
                        />
                        Proficient
                    </label>
                </div>
                <div>
                    <label>
                        Performance:
                        <input
                            type="number"
                            name="skills.performance"
                            value={skills.performance}
                            onChange={handleChange}
                            required
                        />
                    </label>
                    <label>
                        <input
                            type="checkbox"
                            name="skills.performance_pro"
                            checked={skills.performance_pro}
                            onChange={handleChange}
                        />
                        Proficient
                    </label>
                </div>
                <div>
                    <label>
                        Persuasion:
                        <input
                            type="number"
                            name="skills.persuasion"
                            value={skills.persuasion}
                            onChange={handleChange}
                            required
                        />
                    </label>
                    <label>
                        <input
                            type="checkbox"
                            name="skills.persuasion_pro"
                            checked={skills.persuasion_pro}
                            onChange={handleChange}
                        />
                        Proficient
                    </label>
                </div>
                <div>
                    <label>
                        Religion:
                        <input
                            type="number"
                            name="skills.religion"
                            value={skills.religion}
                            onChange={handleChange}
                            required
                        />
                    </label>
                    <label>
                        <input
                            type="checkbox"
                            name="skills.religion_pro"
                            checked={skills.religion_pro}
                            onChange={handleChange}
                        />
                        Proficient
                    </label>
                </div>
                <div>
                    <label>
                        Sleight of Hand:
                        <input
                            type="number"
                            name="skills.sleight_of_hand"
                            value={skills.sleight_of_hand}
                            onChange={handleChange}
                            required
                        />
                    </label>
                    <label>
                        <input
                            type="checkbox"
                            name="skills.sleight_of_hand_pro"
                            checked={skills.sleight_of_hand_pro}
                            onChange={handleChange}
                        />
                        Proficient
                    </label>
                </div>
                <div>
                    <label>
                        Stealth:
                        <input
                            type="number"
                            name="skills.stealth"
                            value={skills.stealth}
                            onChange={handleChange}
                            required
                        />
                    </label>
                    <label>
                        <input
                            type="checkbox"
                            name="skills.stealth_pro"
                            checked={skills.stealth_pro}
                            onChange={handleChange}
                        />
                        Proficient
                    </label>
                </div>
                <div>
                    <label>
                        Survival:
                        <input
                            type="number"
                            name="skills.survival"
                            value={skills.survival}
                            onChange={handleChange}
                            required
                        />
                    </label>
                    <label>
                        <input
                            type="checkbox"
                            name="skills.survival_pro"
                            checked={skills.survival_pro}
                            onChange={handleChange}
                        />
                        Proficient
                    </label>
                </div>
            </form>
        </div>
    );
}
export default CharacterSkills;