import React from "react";

function CreateSavingThrows({ handleChange, charData }) {
    const { saving_throws } = charData;

    return (
        <form>
            <div>
                <label>
                    Strength:
                    <input
                        type="number"
                        name="saving_throws.strength"
                        value={saving_throws.strength}
                        onChange={handleChange}
                        required
                    />
                </label>
                <label>
                    Proficiency:
                    <input
                        type="checkbox"
                        name="saving_throws.strength_pro"
                        checked={saving_throws.strength_pro}
                        onChange={handleChange}
                    />
                </label>
            </div>
            <div>
                <label>
                    Dexterity:
                    <input
                        type="number"
                        name="saving_throws.dexterity"
                        value={saving_throws.dexterity}
                        onChange={handleChange}
                        required
                    />
                </label>
                <label>
                    Proficiency:
                    <input
                        type="checkbox"
                        name="saving_throws.dexterity_pro"
                        checked={saving_throws.dexterity_pro}
                        onChange={handleChange}
                    />
                </label>
            </div>
            <div>
                <label>
                    Constitution:
                    <input
                        type="number"
                        name="saving_throws.constitution"
                        value={saving_throws.constitution}
                        onChange={handleChange}
                        required
                    />
                </label>
                <label>
                    Proficiency:
                    <input
                        type="checkbox"
                        name="saving_throws.constitution_pro"
                        checked={saving_throws.constitution_pro}
                        onChange={handleChange}
                    />
                </label>
            </div>
            <div>
                <label>
                    Intelligence:
                    <input
                        type="number"
                        name="saving_throws.intelligence"
                        value={saving_throws.intelligence}
                        onChange={handleChange}
                        required
                    />
                </label>
                <label>
                    Proficiency:
                    <input
                        type="checkbox"
                        name="saving_throws.intelligence_pro"
                        checked={saving_throws.intelligence_pro}
                        onChange={handleChange}
                    />
                </label>
            </div>
            <div>
                <label>
                    Wisdom:
                    <input
                        type="number"
                        name="saving_throws.wisdom"
                        value={saving_throws.wisdom}
                        onChange={handleChange}
                        required
                    />
                </label>
                <label>
                    Proficiency:
                    <input
                        type="checkbox"
                        name="saving_throws.wisdom_pro"
                        checked={saving_throws.wisdom_pro}
                        onChange={handleChange}
                    />
                </label>
            </div>
            <div>
                <label>
                    Charisma:
                    <input
                        type="number"
                        name="saving_throws.charisma"
                        value={saving_throws.charisma}
                        onChange={handleChange}
                        required
                    />
                </label>
                <label>
                    Proficiency:
                    <input
                        type="checkbox"
                        name="saving_throws.charisma_pro"
                        checked={saving_throws.charisma_pro}
                        onChange={handleChange}
                    />
                </label>
            </div>
        </form>
    );
}

export default CreateSavingThrows;
