import React from "react";

function CreateSkills({ handleChange, charData }) {
  console.log(charData)
  return (
    <form>
      <div>
        <label>
          Acrobatics:
          <input
            type="number"
            name="acrobatics"
            value={charData.acrobatics}
            onChange={handleChange}
            required
          />
          Proficient:
          <input
            type="checkbox"
            name="acrobatics_pro"
            checked={charData.acrobatics_pro}
            onChange={handleChange}
          />
        </label>
      </div>
      <div>
        <label>
          Animal Handling:
          <input
            type="number"
            name="animal_handling"
            value={charData.animal_handling}
            onChange={handleChange}
            required
          />
          Proficient:
          <input
            type="checkbox"
            name="animal_handling_pro"
            checked={charData.animal_handling_pro}
            onChange={handleChange}
          />
        </label>
      </div>
      <div>
        <label>
          Arcana:
          <input
            type="number"
            name="arcana"
            value={charData.arcana}
            onChange={handleChange}
            required
          />
          Proficient:
          <input
            type="checkbox"
            name="arcana_pro"
            checked={charData.arcana_pro}
            onChange={handleChange}
          />
        </label>
      </div>
      <div>
        <label>
          Athletics:
          <input
            type="number"
            name="athletics"
            value={charData.athletics}
            onChange={handleChange}
            required
          />
          Proficient:
          <input
            type="checkbox"
            name="athletics_pro"
            checked={charData.athletics_pro}
            onChange={handleChange}
          />
        </label>
      </div>
      <div>
        <label>
          Deception:
          <input
            type="number"
            name="deception"
            value={charData.deception}
            onChange={handleChange}
            required
          />
          Proficient:
          <input
            type="checkbox"
            name="deception_pro"
            checked={charData.deception_pro}
            onChange={handleChange}
          />
        </label>
      </div>
      <div>
        <label>
          History:
          <input
            type="number"
            name="history"
            value={charData.history}
            onChange={handleChange}
            required
          />
          Proficient:
          <input
            type="checkbox"
            name="history_pro"
            checked={charData.history_pro}
            onChange={handleChange}
          />
        </label>
      </div>
      <div>
        <label>
          Insight:
          <input
            type="number"
            name="insight"
            value={charData.insight}
            onChange={handleChange}
            required
          />
          Proficient:
          <input
            type="checkbox"
            name="insight_pro"
            checked={charData.insight_pro}
            onChange={handleChange}
          />
        </label>
      </div>
      <div>
        <label>
          Intimidation:
          <input
            type="number"
            name="intimidation"
            value={charData.intimidation}
            onChange={handleChange}
            required
          />
          Proficient:
          <input
            type="checkbox"
            name="intimidation_pro"
            checked={charData.intimidation_pro}
            onChange={handleChange}
          />
        </label>
      </div>
      <div>
        <label>
          Investigation:
          <input
            type="number"
            name="investigation"
            value={charData.investigation}
            onChange={handleChange}
            required
          />
          Proficient:
          <input
            type="checkbox"
            name="investigation_pro"
            checked={charData.investigation_pro}
            onChange={handleChange}
          />
        </label>
      </div>
      <div>
        <label>
          Medicine:
          <input
            type="number"
            name="medicine"
            value={charData.medicine}
            onChange={handleChange}
            required
          />
          Proficient:
          <input
            type="checkbox"
            name="medicine_pro"
            checked={charData.medicine_pro}
            onChange={handleChange}
          />
        </label>
      </div>
      <div>
        <label>
          Nature:
          <input
            type="number"
            name="nature"
            value={charData.nature}
            onChange={handleChange}
            required
          />
          Proficient:
          <input
            type="checkbox"
            name="nature_pro"
            checked={charData.nature_pro}
            onChange={handleChange}
          />
        </label>
      </div>
      <div>
        <label>
          Perception:
          <input
            type="number"
            name="perception"
            value={charData.perception}
            onChange={handleChange}
            required
          />
          Proficient:
          <input
            type="checkbox"
            name="perception_pro"
            checked={charData.perception_pro}
            onChange={handleChange}
          />
        </label>
      </div>
      <div>
        <label>
          Performance:
          <input
            type="number"
            name="performance"
            value={charData.performance}
            onChange={handleChange}
            required
          />
          Proficient:
          <input
            type="checkbox"
            name="performance_pro"
            checked={charData.performance_pro}
            onChange={handleChange}
          />
        </label>
      </div>
      <div>
        <label>
          Persuasion:
          <input
            type="number"
            name="persuasion"
            value={charData.persuasion}
            onChange={handleChange}
            required
          />
          Proficient:
          <input
            type="checkbox"
            name="persuasion_pro"
            checked={charData.persuasion_pro}
            onChange={handleChange}
          />
        </label>
      </div>
      <div>
        <label>
          Religion:
          <input
            type="number"
            name="religion"
            value={charData.religion}
            onChange={handleChange}
            required
          />
          Proficient:
          <input
            type="checkbox"
            name="religion_pro"
            checked={charData.religion_pro}
            onChange={handleChange}
          />
        </label>
      </div>
      <div>
        <label>
          Sleight of Hand:
          <input
            type="number"
            name="sleight_of_hand"
            value={charData.sleight_of_hand}
            onChange={handleChange}
            required
          />
          Proficient:
          <input
            type="checkbox"
            name="sleight_of_hand_pro"
            checked={charData.sleight_of_hand_pro}
            onChange={handleChange}
          />
        </label>
      </div>
      <div>
        <label>
          Stealth:
          <input
            type="number"
            name="stealth"
            value={charData.stealth}
            onChange={handleChange}
            required
          />
          Proficient:
          <input
            type="checkbox"
            name="stealth_pro"
            checked={charData.stealth_pro}
            onChange={handleChange}
          />
        </label>
      </div>
      <div>
        <label>
          Survival:
          <input
            type="number"
            name="survival"
            value={charData.survival}
            onChange={handleChange}
            required
          />
          Proficient:
          <input
            type="checkbox"
            name="survival_pro"
            checked={charData.survival_pro}
            onChange={handleChange}
          />
        </label>
      </div>


    </form>
  );
}

export default CreateSkills;
