"""empty message

Revision ID: 6e083c7f05b2
Revises: 
Create Date: 2024-06-10 17:18:27.177116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e083c7f05b2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('characters_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('klass', sa.String(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('background', sa.String(), nullable=True),
    sa.Column('race', sa.String(), nullable=True),
    sa.Column('xp', sa.Integer(), nullable=True),
    sa.Column('alignment', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('attack_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('attack_bonus', sa.Integer(), nullable=True),
    sa.Column('dmg', sa.Integer(), nullable=True),
    sa.Column('tipe', sa.String(), nullable=True),
    sa.Column('character_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters_table.id'], name=op.f('fk_attack_table_character_id_characters_table')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipment_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipment', sa.String(), nullable=True),
    sa.Column('equipment_stat', sa.Integer(), nullable=True),
    sa.Column('character_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters_table.id'], name=op.f('fk_equipment_table_character_id_characters_table')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feats_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('features', sa.String(), nullable=True),
    sa.Column('traits', sa.String(), nullable=True),
    sa.Column('character_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters_table.id'], name=op.f('fk_feats_table_character_id_characters_table')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('health_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('armor_class', sa.Integer(), nullable=True),
    sa.Column('initiative', sa.Integer(), nullable=True),
    sa.Column('speed', sa.Integer(), nullable=True),
    sa.Column('max_hp', sa.Integer(), nullable=True),
    sa.Column('current_hp', sa.Integer(), nullable=True),
    sa.Column('temp_hp', sa.Integer(), nullable=True),
    sa.Column('hit_total', sa.Integer(), nullable=True),
    sa.Column('hit_dice', sa.Integer(), nullable=True),
    sa.Column('character_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters_table.id'], name=op.f('fk_health_table_character_id_characters_table')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('misc_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inspiration', sa.Integer(), nullable=True),
    sa.Column('prof_bonus', sa.Integer(), nullable=True),
    sa.Column('character_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters_table.id'], name=op.f('fk_misc_table_character_id_characters_table')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('other_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('other_prof', sa.String(), nullable=True),
    sa.Column('languages', sa.String(), nullable=True),
    sa.Column('character_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters_table.id'], name=op.f('fk_other_table_character_id_characters_table')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('personal_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('personality_traits', sa.String(), nullable=True),
    sa.Column('ideals', sa.String(), nullable=True),
    sa.Column('bonds', sa.String(), nullable=True),
    sa.Column('flaws', sa.String(), nullable=True),
    sa.Column('character_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters_table.id'], name=op.f('fk_personal_table_character_id_characters_table')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dm', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('character_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns_table.id'], name=op.f('fk_roles_table_campaign_id_campaigns_table')),
    sa.ForeignKeyConstraint(['character_id'], ['characters_table.id'], name=op.f('fk_roles_table_character_id_characters_table')),
    sa.ForeignKeyConstraint(['user_id'], ['users_table.id'], name=op.f('fk_roles_table_user_id_users_table')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('saving_throws',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strength', sa.Integer(), nullable=True),
    sa.Column('strength_pro', sa.Boolean(), nullable=True),
    sa.Column('dexterity', sa.Integer(), nullable=True),
    sa.Column('dexterity_pro', sa.Boolean(), nullable=True),
    sa.Column('constitution', sa.Integer(), nullable=True),
    sa.Column('constitution_pro', sa.Boolean(), nullable=True),
    sa.Column('intelligence', sa.Integer(), nullable=True),
    sa.Column('intelligence_pro', sa.Boolean(), nullable=True),
    sa.Column('wisdom', sa.Integer(), nullable=True),
    sa.Column('wisdom_pro', sa.Boolean(), nullable=True),
    sa.Column('charisma', sa.Integer(), nullable=True),
    sa.Column('charisma_pro', sa.Boolean(), nullable=True),
    sa.Column('character_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters_table.id'], name=op.f('fk_saving_throws_character_id_characters_table')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skills_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('acrobatics', sa.Integer(), nullable=True),
    sa.Column('acrobatics_pro', sa.Boolean(), nullable=True),
    sa.Column('animal_handling', sa.Integer(), nullable=True),
    sa.Column('animal_handling_pro', sa.Boolean(), nullable=True),
    sa.Column('arcana', sa.Integer(), nullable=True),
    sa.Column('arcana_pro', sa.Boolean(), nullable=True),
    sa.Column('athletics', sa.Integer(), nullable=True),
    sa.Column('athletics_pro', sa.Boolean(), nullable=True),
    sa.Column('deception', sa.Integer(), nullable=True),
    sa.Column('deception_pro', sa.Boolean(), nullable=True),
    sa.Column('history', sa.Integer(), nullable=True),
    sa.Column('history_pro', sa.Boolean(), nullable=True),
    sa.Column('insight', sa.Integer(), nullable=True),
    sa.Column('insight_pro', sa.Boolean(), nullable=True),
    sa.Column('intimidation', sa.Integer(), nullable=True),
    sa.Column('intimidation_pro', sa.Boolean(), nullable=True),
    sa.Column('investigation', sa.Integer(), nullable=True),
    sa.Column('investigation_pro', sa.Boolean(), nullable=True),
    sa.Column('medicine', sa.Integer(), nullable=True),
    sa.Column('medicine_pro', sa.Boolean(), nullable=True),
    sa.Column('nature', sa.Integer(), nullable=True),
    sa.Column('nature_pro', sa.Boolean(), nullable=True),
    sa.Column('perception', sa.Integer(), nullable=True),
    sa.Column('perception_pro', sa.Boolean(), nullable=True),
    sa.Column('performance', sa.Integer(), nullable=True),
    sa.Column('performance_pro', sa.Boolean(), nullable=True),
    sa.Column('persuasion', sa.Integer(), nullable=True),
    sa.Column('persuasion_pro', sa.Boolean(), nullable=True),
    sa.Column('religion', sa.Integer(), nullable=True),
    sa.Column('religion_pro', sa.Boolean(), nullable=True),
    sa.Column('sleight_of_hand', sa.Integer(), nullable=True),
    sa.Column('sleight_of_hand_pro', sa.Boolean(), nullable=True),
    sa.Column('stealth', sa.Integer(), nullable=True),
    sa.Column('stealth_pro', sa.Boolean(), nullable=True),
    sa.Column('survival', sa.Integer(), nullable=True),
    sa.Column('survival_pro', sa.Boolean(), nullable=True),
    sa.Column('character_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters_table.id'], name=op.f('fk_skills_table_character_id_characters_table')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stats_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strength_mod', sa.Integer(), nullable=True),
    sa.Column('strength', sa.Integer(), nullable=True),
    sa.Column('dexterity_mod', sa.Integer(), nullable=True),
    sa.Column('dexterity', sa.Integer(), nullable=True),
    sa.Column('constitution_mod', sa.Integer(), nullable=True),
    sa.Column('constitution', sa.Integer(), nullable=True),
    sa.Column('intelligence_mod', sa.Integer(), nullable=True),
    sa.Column('intelligence', sa.Integer(), nullable=True),
    sa.Column('wisdom_mod', sa.Integer(), nullable=True),
    sa.Column('wisdom', sa.Integer(), nullable=True),
    sa.Column('charisma_mod', sa.Integer(), nullable=True),
    sa.Column('charisma', sa.Integer(), nullable=True),
    sa.Column('wis_perception', sa.Integer(), nullable=True),
    sa.Column('wis_perception_mod', sa.Integer(), nullable=True),
    sa.Column('character_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters_table.id'], name=op.f('fk_stats_table_character_id_characters_table')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stats_table')
    op.drop_table('skills_table')
    op.drop_table('saving_throws')
    op.drop_table('roles_table')
    op.drop_table('personal_table')
    op.drop_table('other_table')
    op.drop_table('misc_table')
    op.drop_table('health_table')
    op.drop_table('feats_table')
    op.drop_table('equipment_table')
    op.drop_table('attack_table')
    op.drop_table('users_table')
    op.drop_table('characters_table')
    op.drop_table('campaigns_table')
    # ### end Alembic commands ###
